name: Example Workflow

on:
  workflow_run:
    workflows: ["ecample_trigger.yml"]
    types:
      - completed

jobs:
  example-job:
    runs-on: ubuntu-latest

    steps:
      - name: Display message
        run: echo "The 'ecample' workflow has completed."
