name: PR - grey skipped workflow

on:
 - pull_request 

jobs:
  kalle-checksum-verification:
    runs-on: ubuntu-latest
    outputs:
      step-status: ${{ steps.step-status.outputs.status }}
    steps:
      - name: Check for failed workflows
        id: step-status
        run: |
          echo "This workflow is intentionally skipped and greyed out. It will not be executed automatically but can be triggered manually."
          

  notify-on-success:
    needs: kalle-checksum-verification
    runs-on: ubuntu-latest
    if: ${{ needs.kalle-checksum-verification.outputs.step-status == 'success' }}
    steps:
      - name: Notify on Success
        run: |
          echo "The kalle-checksum-verification step was successful. Notify accordingly."
          exit 0

  notify-on-status:
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: "Plan faild send failure notification"
        if: ${{ steps.step-status.outputs.status }} != 'success'
        uses: slackapi/slack-github-action@v1.23.0

      - name: "Plan success send success notification"
        if: ${{ steps.step-status.outputs.status }} == 'success'
        uses: slackapi/slack-github-action@v1.23.0

  notify-on-failure:
    needs: kalle-checksum-verification
    runs-on: ubuntu-latest
    if: ${{ needs.kalle-checksum-verification.outputs.step-status == 'failure' }}
    steps:
      - name: Notify on Failure
        run: echo "The kalle-checksum-verification step failed. Notify accordingly."


