name: Push - greyed outworkflows due main branch

on:
  push:
    branches:
      - main

jobs:
  build_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: echo "Building the project"
