name: Slack Notification Aggregator

on:
  # - pull_request
   workflow_run:
      workflows: ["kalle-checksum.yaml", "kalle-ops-sop.yaml", "workflow_01.yml", "log-alarm-forwarder.yaml", "Second_Workflow.yml", "workflow_01.yml", "skipped_workflow_sim.yml", "greyed_out_workflows.yml", "grey_skipped-workflow.yml"]
     

jobs:
  check_and_notify:
    runs-on: ubuntu-22.04
    steps:
      # - name: Check individual workflow statuses
      #   run: |
      #     for workflow in workflow_runs {
      #       if (workflow.conclusion != 'success') {
      #         exit 1
      #       }
      #     }

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          payload: |
            {
              "text": "@Misk for Review - GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }} \n *Created by:* <${{ github.event.pull_request.user.login }}>",
              "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "@Misk for Review GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }} \n *Created by:* <${{ github.event.pull_request.user.login }}>"
                }
              }
            ] 
            }
        env:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

