---
name: Send custom JSON data to Slack workflow

on:
  - pull_request

jobs:
  verify_workflow_started:
    runs-on: ubuntu-latest
    steps:
      - name: Check for failed workflows
        run: |
          for workflow_run in workflow_runs {
            if (workflow_run.status != 'success') {
              failed_workflows=true
              break
            }
          }

          if (!failed_workflows) {
            echo "All workflows completed successfully, sending notification to Slack"

            - name: Send custom JSON data to Slack workflow
              id: slack
              uses: slackapi/slack-github-action@v1.24.0
              with:
                channel-id: C038JK97W1G
                payload: |
                {
                  "text": "@Michel workflow_triggers PR for Review - GitHub Action build result: <span class="math-inline">\{\{ job\.status \}\}\\n</span>{{ github.event.pull_request.html_url || github.event.head_commit.url }} \n *Created by:* <${{ github.event.pull_request.user.login }}>",
                  "blocks": [
                    {
                      "type": "section",
                      "text": {
                        "type": "mrkdwn",
                        "text": "@Michel workflow_triggers PR for Review GitHub Action build result: <span class="math-inline">\{\{ job\.status \}\}\\n</span>{{ github.event.pull_request.html_url || github.event.head_commit.url }} \n *Created by:* <${{ github.event.pull_request.user.login }}>"
                      }
                    }
                  ]
                }

              env:
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
                SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
          }
          else {
            echo "One or more workflows failed. Not sending notification to Slack"
          }
     
	 