---
name: Send custom JSON data to Slack workflow

on:
  - pull_request
#  workflow_run:
#     workflows: ["kalle-checksum.yaml", "kalle-ops-sop.yaml", "workflow_01.yml", "log-alarm-forwarder.yaml", "Second_Workflow.yml", "workflow_01.yml", "skipped_workflow_sim.yml", "greyed_out_workflows.yml", "grey_skipped-workflow.yml"]
#     types: [completed]

jobs:
  verify_workflow_started:
   runs-on: ubuntu-latest
   steps:
      - name: Check for failed workflows step
        run: |
          echo "Send slack notity step"

  new_push_job:
    runs-on: ubuntu-latest
    steps:
      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.18.0
        with:
          payload: |
            {
              "text": "@Michel .github/workflows/slack-PR-notify.yml PR for Review - GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }} \n *Created by:* <${{ github.event.pull_request.user.login }}>",
              "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "@Michel .github/workflows/slack-PR-notify.yml PR for Review GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }} \n *Created by:* <${{ github.event.pull_request.user.login }}>"
                }
              }
            ] 
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BOT_TOKEN}}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK