name: Slack Notification Aggregator

on:
  workflow_run:
    workflows: ["atg-checksum.yaml", "atg-ops-sop.yaml", "atg-team-debug.yaml", "atgcsum.yaml", "log-alarm-forwarder.yaml", "node-dt-collector.yaml", "ocp-insight.yaml", "secure-forwarder.yaml"]
    types: [completed]

jobs:
  check_and_notify:
    runs-on: ubuntu-22.04
    steps:
      - name: Check individual workflow statuses
        run: |
          for workflow in workflow_runs {
            if (workflow.conclusion != 'success') {
              exit 1
            }
          }

      - id: slack
        name: Send custom JSON data to Slack workflow
        run: |
          payload: |
            {
              "text": "@ocp-sre for Review - GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }} \n *Created by:* <${{ github.event.pull_request.user.login }}>",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "@ocp-sre for Review GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }} \n *Created by:* <${{ github.event.pull_request.user.login }}>"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

