name: Workflow 1

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo "Running step 1 in Workflow 1"

      # Add more steps as needed

  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Step 2
        run: echo "Running step 2 in Workflow 1"

      # Add more steps as needed
