name: Workflow 2

on:
  workflow_run:
    workflows: ["workflow1.yml"]
 

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: need to get the branch
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.workflow_run.head_branch}}

      - name: Triggered by Workflow 1 completion
        run: echo "Workflow 2 triggered by Workflow 1 completion"

      # Add more steps as needed
