name: Workflow_02
on:
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["Workflow_01"]
    types:
      - completed 
jobs:
  test-1:
    runs-on: ubuntu-22.04
   
    steps:
      - run: echo 'The triggering workflow passed'

  on-failure:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
  
   