name: workflow-2
on:
  pull_request:
    types: [review_requested]
jobs:
  workflow-2:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'A review from octo-team was requested- From workflow-2'
  
   