name: First Workflow

on:
  pull_request:
    branches:
      - main

jobs:
  first_job:
    runs-on: ubuntu-22.04
    steps:
      - name: Build the project
        run: |
          echo "Building the project..."
          
      - name: Upload the build artifacts
        run: |
          echo "Uploading the build artifacts..."
 
