name: learn-github-actions-workflow1
on:
   pull_request:
    branches:
      - main
jobs:
  workflow-1:
    runs-on: ubuntu-22.04
    steps:
      - run: echo 'A review was requested- From workflow-1'
