name: workflow-2
pull_request:
    types: [review_requested]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'A review from octo-team was requested- From workflow-2'