name: Workflow_02
on:
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: ["Workflow_01"]
    types:
      - completed 
jobs:
  test-1:
    runs-on: ubuntu-22.04
   
    steps:
      - run: echo 'The triggering workflow passed'
  test-2:
    runs-on: ubuntu-22.04
  
    steps:
      - run: echo 'The triggering workflow failed'
  
   